# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160321_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balanced_bank_account_href',
            new_name='stripe_account_token',
        ),
    ]
