# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160327_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_card_token',
        ),
    ]
