# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_stripe_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_cc_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
