# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160717_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
