# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_stripeevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeevent',
            old_name='data',
            new_name='message_text',
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='verification_fields',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
