# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20160722_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='stripe_id',
            new_name='account_id',
        ),
    ]
