# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160722_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_cc_token',
            new_name='stripe_bank_account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='stripe_customer_token',
            new_name='stripe_card',
        ),
    ]
