# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160723_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
