# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='external_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
