# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_stripeaccount_external_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='external_account',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='tos_acceptance_date',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='tos_acceptance_ip',
        ),
        migrations.AddField(
            model_name='user',
            name='tos_acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tos_acceptance_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
