# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160729_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='available_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
