# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_stripeaccount_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
