# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_stripeevent_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeEvent',
        ),
        migrations.DeleteModel(
            name='StripeAccount',
        ),
    ]
