# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-10 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20160803_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last4',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
