# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-15 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20170410_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brand',
            new_name='card_brand',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last4',
            new_name='card_last4',
        ),
    ]
