# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('secret_key', models.CharField(blank=True, max_length=100)),
                ('public_key', models.CharField(blank=True, max_length=100)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('verification', models.TextField(blank=True, default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('message_text', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
