# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
