# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripeevent_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
