# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_stripeevent_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
