# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripeevent_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='secret_key',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
