FROM quay.io/deis/base:0.3.0

ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends python2.7 libpython2.7 \
    gettext build-essential python-dev python-pip python-setuptools \
    postgresql-client libpq-dev \
    python-cffi-backend libffi-dev

WORKDIR /app

COPY ./requirements.txt /app/
COPY ./requirements-test.txt /app/
RUN pip install --no-cache-dir -r requirements-test.txt

COPY ./requirements-dev.txt /app/
RUN pip install --no-cache-dir -r requirements-dev.txt
