# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20160221_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
