# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0015_issue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('provider', models.CharField(choices=[(b'Stripe', b'Stripe')], default=b'Stripe', max_length=255)),
                ('confirmation', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='auctions.Bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[(b'Submitted', b'Submitted'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Rejected', b'Rejected')], default=b'Submitted', max_length=255),
        ),
    ]
