# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20160327_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[(b'Submitted', b'Submitted'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Rejected', b'Rejected'), (b'Paid', b'Paid')], default=b'Submitted', max_length=255),
        ),
    ]
