# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20160330_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy')], default=b'', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='payout',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='offer',
            name='provider',
            field=models.CharField(choices=[(b'Stripe', b'Stripe'), (b'PayPal', b'PayPal')], default=b'Stripe', max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='provider',
            field=models.CharField(choices=[(b'Stripe', b'Stripe'), (b'PayPal', b'PayPal')], default=b'PayPal', max_length=255),
        ),
    ]
