# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20160330_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy')], default=b'', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_fees', to='auctions.Offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy')], default=b'', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_fees', to='auctions.Payout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
