# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20160407_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerfee',
            old_name='type',
            new_name='fee_type',
        ),
        migrations.RenameField(
            model_name='payoutfee',
            old_name='type',
            new_name='fee_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='api_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='api_success',
            field=models.BooleanField(default=False),
        ),
    ]
