# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20160408_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerfee',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_fees', to='auctions.Offer'),
        ),
        migrations.AlterField(
            model_name='payoutfee',
            name='payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_fees', to='auctions.Payout'),
        ),
    ]
