# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 12:06
from __future__ import unicode_literals

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20160408_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='transaction_key',
            field=models.CharField(blank=True, default=auctions.models.uuid_please, max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='transaction_key',
            field=models.CharField(blank=True, default=auctions.models.uuid_please, max_length=255),
        ),
    ]
