# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20160408_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payout',
            name='charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
