# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20160409_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='fee',
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
