# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20160410_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
