# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20160519_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund')], default=b'', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_credits', to='auctions.Payout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='offerfee',
            name='fee_type',
            field=models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund')], default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='payoutfee',
            name='fee_type',
            field=models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund')], default=b'', max_length=255),
        ),
    ]
