# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20160603_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[(b'Submitted', b'Submitted'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Rejected', b'Rejected'), (b'Requested', b'Requested'), (b'Paid', b'Paid')], default=b'Submitted', max_length=255),
        ),
        migrations.AlterField(
            model_name='payoutcredit',
            name='payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_credit', to='auctions.Payout'),
        ),
    ]
