# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20160717_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='provider',
            field=models.CharField(choices=[(b'Stripe', b'Stripe'), (b'PayPal', b'PayPal')], default=b'Stripe', max_length=255),
        ),
    ]
