# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20160806_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 5, 13, 52, 34, 685137, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 13, 52, 42, 862740, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
