# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20160806_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='offerfee',
            name='fee_type',
            field=models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund'), (b'surplus', b'surplus')], default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='payoutcredit',
            name='fee_type',
            field=models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund'), (b'surplus', b'surplus')], default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='payoutfee',
            name='fee_type',
            field=models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund'), (b'surplus', b'surplus')], default=b'', max_length=255),
        ),
    ]
