# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20160905_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 5, 14, 40, 17, 337406, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 14, 40, 22, 234927, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 5, 14, 40, 27, 114691, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 14, 40, 30, 500397, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
