# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20160826_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
