# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20160905_1440'),
        ('auctions', '0035_auto_20160826_1223'),
    ]

    operations = [
    ]
