# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 8, 12, 50, 38, 512292, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 8, 12, 50, 49, 786526, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 8, 12, 50, 53, 579917, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payout',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 8, 12, 50, 57, 499702, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
