# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20160908_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[(b'PayPal', b'PayPal'), (b'Stripe', b'Stripe'), (b'codesy', b'codesy'), (b'refund', b'refund'), (b'surplus', b'surplus')], default=b'', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_credit', to='auctions.Payout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
